#!/usr/bin/env python3
"""Generate the dedicated QG1L (reduced-gravity 1-layer) DA report.

JSON-only generator (no QG/neural code imports). It consumes the committed
S1-QG1L structural-error results under ``reports/qg/outputs/qg_s1_qg1l_rscale/``
plus the ``qg_settings.json`` QGConfig snapshot, and renders a self-contained
Markdown report focused on the reduced-gravity model-error case:

- the QG1L governing equations,
- the structural-error framing (1-layer vs 2-layer truth; the over-trusted
  nonlocal psi obs),
- the observation-variance r-scale sweep (rs = 1 / 100 / 1e4) per field,
- the local PV (q-obs) reference.

Run from the repository root::

    python reports/qg/generate_qg1l_report.py
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

FIELD_LABELS = {"q": "PV q", "psi": "streamfunction ψ"}
LAYER_LABELS = {"layer1": "upper (layer 1)", "full": "full state"}

_RSDIR = "qg_s1_qg1l_rscale"

_EQUATIONS = r"""
### 1.1 Reduced-gravity single-layer model (QG1LDynamics)

The structural-error DA model is a reduced-gravity **single-layer** QG on a
double-periodic β-plane: one active upper layer over a motionless deep layer.
The PV anomaly relative to the β-plane background is

$$ q = \nabla^2 \psi - \frac{\psi}{r_d^2}, \qquad
    \psi = -\left(\nabla^2 + r_d^{-2}\right)^{-1} q , $$

with masked zero-mode inversion ($K^2 = 0 \Rightarrow \psi = 0$). Evolution is
flux-form advection with RK4 and the pyqg exponential filter,

$$ \frac{d q}{dt} = -J(\psi,\, q + \beta y) - r_{\mathrm{ek}}\,\nabla^2 \psi
    + \mathrm{curl}\,\tau , $$

where $-r_{\mathrm{ek}}\nabla^2\psi$ is linear bottom drag and
$\mathrm{curl}\,\tau$ is the same moving-storm wind-stress-curl forcing as the
two-layer `QGDynamics`. `param_names = [β, rd, rek, U1]` (rd fixed at
construction). State layout is flattened `[ny·nx]` (single active layer).

### 1.2 Structural-error setting

The **truth** is generated by the 2-layer Phillips QG model (the same forcing,
params and spinup as the S0/S1 QG2L runs). The DA filter instead uses the
1-layer model above as its forecast model against the 2-layer truth — a
deliberate mis-specification of the unresolved lower layer. Because the
observations are the **nonlocal upper-layer streamfunction ψ₁** (psi-obs,
inverted to PV after spectral upsampling), and the 1-layer model cannot absorb
the lower-layer PV the ψ observations imply, the filter over-trusts them and
produces analyses worse than the free forecast at the nominal observation
noise.
"""

_FRAMING = r"""
The DA uses the ETKF (N = 80, inflation 1.0, Gaspari–Cohn localization radius 6)
at full resolution (da_nx = 64, truth at 64×64), psi-obs (upper-layer
streamfunction, random columns, cols = 4), 1% obs noise, lag 1.0 d.

`obs_var_r_scale` multiplies the observation-noise variance `r_var` on both the
q- and psi-obs paths. Scaling R up models the error that the perfect-forecast
ensemble assumption understates when a structurally-wrong DA model makes the
psi observations mutually inconsistent with the model, i.e. it inflates the
observation-error budget to reflect the unmodelled structural error. Default
= 1.0 reproduces the baseline behaviour (DA worse than the free forecast).
"""


def load_json(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def fmt_ev(x) -> str:
    return f"{x:+.3f}" if isinstance(x, (int, float)) else str(x)


def fmt_rmse(x) -> str:
    if abs(x) < 1e-3:
        return f"{x:.2e}"
    return f"{x:.3g}"


def fmt_improv(x) -> str:
    return f"{x:.2f}"


def _find_rs(rsdir: Path, field: str, tag: str) -> Path | None:
    for p in rsdir.glob("*.json"):
        if f"_{field}_" in p.name and (
            f"_{tag}_" in p.name or p.name.endswith(f"_{tag}.json")
        ):
            return p
    return None


def _scenario(rsdir: Path, field: str, tag: str) -> dict | None:
    p = _find_rs(rsdir, field, tag)
    if p is None:
        return None
    d = load_json(p)
    return d["scenarios"].get("test_s1_qg1l")


def _per_field_table(s1: dict) -> list[str]:
    rows = []
    mpf = s1["metrics_per_field"]
    for fld in ("q", "psi"):
        for lyr in ("layer1", "full"):
            if lyr not in mpf[fld]:
                continue
            m = mpf[fld][lyr]
            rows.append(f"| {FIELD_LABELS[fld]} | {LAYER_LABELS[lyr]} | "
                        f"{fmt_rmse(m['rmse'])} | {fmt_rmse(m['rmse_free'])} | "
                        f"{fmt_improv(m['improv'])} | {fmt_ev(m['ev'])} | "
                        f"{fmt_ev(m['ev_free'])} |")
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--json-root", default=str(ROOT / "reports/qg/outputs"))
    ap.add_argument("--settings", default=str(ROOT / "reports/qg/outputs/qg_settings.json"))
    ap.add_argument("--out", default=str(ROOT / "reports/qg/outputs/qg1l_report.md"))
    args = ap.parse_args()

    root = Path(args.json_root)
    settings = load_json(Path(args.settings))
    rsdir = root / _RSDIR

    fsm = {"rs1": 1.0, "rs100": 100.0, "rs1e4": 1e4}

    missing = []
    for field, tag in (("psi", "rs1"), ("psi", "rs100"), ("psi", "rs1e4"),
                       ("q", "rs1")):
        if _find_rs(rsdir, field, tag) is None:
            missing.append(f"{_RSDIR} {field} {tag}")

    md = []
    add = md.append

    add("# QG1L DA Report — Reduced-Gravity Single-Layer Structural Error")
    add("")
    add("**Date:** 2026-09-02")
    add("**Branch (report):** master")
    add("**Source JSONs:** `reports/qg/outputs/qg_s1_qg1l_rscale/`.")
    add("")

    add("## 1. System and governing equations")
    add("")
    add(_EQUATIONS.strip())
    add("")
    add("## 2. Structural-error setting and r-scale sweep")
    add("")
    add(_FRAMING.strip())
    add("")
    add("### Base configuration")
    add("")
    add(f"- Domain `L = {settings['L']:.0f}` m, grid `nx = ny = 64` "
        f"(state_dim = {settings['state_dim']}), dt = {settings['dt']:.0f} s, "
        f"steps_per_day = {settings['steps_per_day']}.")
    add(f"- Assimilation window {settings['window_days']:.0f} d "
        f"({settings['num_steps']} steps), spinup {settings['spinup_years']:.0f} y, "
        f"{settings['num_windows']} windows.")
    add(f"- Physics β = {settings['beta']:.1e}, rd = {settings['rd']:.0f} m, "
        f"rek = {settings['rek']:.3e}; moving-storm wind "
        f"`wind_amp = {settings['wind_amp']:.0e}`.")
    add("")

    add("## 3. Results — obs-variance r-scale sweep (psi-obs)")
    add("")
    add("### 3.1 Headline (psi-obs)")
    add("")
    add("| r_scale | DA RMSE | Free RMSE | improv | EV_full | EV_free |")
    add("|---|---|---|---|---|---|")
    for tag, rv in sorted(fsm.items(), key=lambda kv: kv[1]):
        s1 = _scenario(rsdir, "psi", tag)
        if s1 is None:
            continue
        add(f"| {rv:g} | {fmt_rmse(s1['rmse_mean'])} | "
            f"{fmt_rmse(s1['forecast_rmse_mean'])} | "
            f"{fmt_improv(s1['forecast_improvement'])} | "
            f"{fmt_ev(s1['expvar_full'])} | {fmt_ev(s1['expvar_free'])} |")
    add("")
    add("`improv` = forecast improvement (DA-RMSE / free-RMSE; > 1 means the DA "
        "beats the free forecast). EV = pooled explained variance.")
    add("")
    add("### 3.2 Per-field, by r_scale")
    add("")
    for tag, rv in sorted(fsm.items(), key=lambda kv: kv[1]):
        s1 = _scenario(rsdir, "psi", tag)
        if s1 is None:
            continue
        add(f"**r_scale = {rv:g}**")
        add("")
        add("| field | layer | DA RMSE | Free RMSE | improv | EV | EV_free |")
        add("|---|---|---|---|---|---|---|")
        add("\n".join(_per_field_table(s1)))
        add("")
    add("### 3.3 S0 (error-free) anchor under psi-obs")
    add("")
    s1 = _scenario(rsdir, "psi", "rs1")
    if s1 is not None:
        p = _find_rs(rsdir, "psi", "rs1")
        s0 = load_json(p)["scenarios"]["test_s0"]
        add("| field | layer | DA RMSE | Free RMSE | improv | EV | EV_free |")
        add("|---|---|---|---|---|---|---|")
        add("\n".join(_per_field_table(s0)))
        add("")
        add("The error-free S0 (2-layer DA) benchmark is unaffected by the "
            "r-scale (R-inflation only matters where the model is wrong) and "
            "shows healthy positive EV before any structural error is added.")
    add("")

    add("## 4. Local PV (q-obs) reference")
    add("")
    s1 = _scenario(rsdir, "q", "rs1")
    if s1 is not None:
        add("For comparison, the same structural-error S1 with **local upper-layer "
            "PV observations** (q-obs) at r_scale = 1:")
        add("")
        add("| field | layer | DA RMSE | Free RMSE | improv | EV | EV_free |")
        add("|---|---|---|---|---|---|---|")
        add("\n".join(_per_field_table(s1)))
        add("")
        add("A spatially-local PV observation is far more robust to the "
            "unresolved lower layer than the nonlocal psi columns: it nearly "
            "reaches the free-forecast skill for q (improv ~0.96) and beats it "
            "for the streamfunction (improv ~1.19), even at nominal R.")
    add("")

    add("## 5. Interpretation")
    add("")
    add("- At the nominal R the 1-layer filter is **worse than the free forecast** "
        "(improv ~0.39, EV ≈ −11): with the wrong (too-simple) forecast model, "
        "the nonlocal psi observations are mutually inconsistent with the model "
        "and over-trusted — the analysis is pulled toward an inconsistent "
        "observation set rather than the flow the model can represent.")
    add("- Inflating the observation-error variance `obs_var_r_scale` "
        "monotonically recovers skill toward the free-forecast limit "
        "(improv 0.39 → 0.42 → 0.81 for the PV-q field at rs = 1/100/1e4) but "
        "**does not cross 1.0**: at full-resolution da_nx=64 a scale-relative "
        "R-inflation degrades skill, so R-inflation is a partial correction "
        "only, not a fix for the structural error.")
    add("- The **observation geometry** dominates: switching from nonlocal "
        "psi-columns to local q-obs at nominal R nearly matches the free-forecast "
        "quality for the PV field (improv ~0.96) and exceeds it for the "
        "streamfunction (improv ~1.19). For a structurally-wrong forecast model, "
        "a local, model-consistent observation type is the most effective lever.")
    add("")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(md))
    print(f"wrote {out}")
    if missing:
        print("WARNING: missing JSONs:", missing)
        raise SystemExit(2)


if __name__ == "__main__":
    main()
