"""Generate one contiguous chunk of QG S0/S1 truth windows for one split
(train/val/test), as a single task of a SLURM array job.

Each window is written to its own file (`{out_dir}/{split}/window_{idx:05d}.pt`)
so a crashed/timed-out task never corrupts already-finished windows and the
reassembly step (`assemble_qg_windows.py`) can simply glob + sort by index.

Windows are independent by construction (`QGS01Dataset._generate_truth` seeds
a fresh `RandomState(cfg.seed + i)` per index `i`), so any subset of indices
can be generated by any worker in any order with no coordination and still
match what a full serial run over the same (cfg, n) would produce.
"""
import argparse
import os
import sys
import time

import torch

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))

from data.qg import QGConfig, QGS01Dataset

# Distinct seed bases per split so train/val/test occupy disjoint index
# spaces even though each internally indexes windows 0..n_total-1. Offsets
# are far larger than any per-window seed-arithmetic span (seed + 4000 + i*101
# for i up to ~1000 spans ~101000) to guarantee no cross-split collision.
SPLIT_SEED_BASE = {"train": 42, "val": 10_042, "test": 20_042}
SPLIT_SIZE = {"train": 1000, "val": 100, "test": 100}


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--split", required=True, choices=["train", "val", "test"])
    p.add_argument("--start", type=int, required=True)
    p.add_argument("--count", type=int, required=True)
    p.add_argument("--out-dir", required=True)
    args = p.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    n_total = SPLIT_SIZE[args.split]
    cfg = QGConfig(nx=64, dt=7200.0, seed=SPLIT_SEED_BASE[args.split],
                   num_windows=n_total)
    indices = list(range(args.start, min(args.start + args.count, n_total)))
    if not indices:
        print(f"[{args.split}] nothing to do for start={args.start}")
        return

    out_dir = os.path.join(args.out_dir, args.split)
    os.makedirs(out_dir, exist_ok=True)

    print(f"[{args.split}] device={device} indices={indices[0]}..{indices[-1]} "
          f"({len(indices)} windows)", flush=True)
    t0 = time.time()
    windows = QGS01Dataset._generate_truth(cfg, n_total, device=device, indices=indices)
    for idx, w in zip(indices, windows):
        torch.save(w, os.path.join(out_dir, f"window_{idx:05d}.pt"))
    print(f"[{args.split}] wrote {len(indices)} windows in {time.time()-t0:.1f}s", flush=True)


if __name__ == "__main__":
    main()
